name: Maven central workflow

on:
  push:
    branches: ['FOLIO-4126-maven-workflows-1']
  pull_request:
  workflow_dispatch:

jobs:
  maven:
    uses: folio-org/.github/.github/workflows/maven.yml@FOLIO-4126-maven-workflows-1
    # Only handle push events from the main branch or tags, to decrease PR noise
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      docker-health-command: 'wget --no-verbose --tries=1 --spider http://localhost:8081/admin/health || exit 1'
      docker-label-documentation: 'https://github.com/folio-org/mod-settings/tree/master/doc'
      do-maven-deploy: true
